---
title: "Dilution Scheme"
author: "Omar Elashkar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Dilution Scheme}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.width = 15,
  fig.height = 10
)
```

```{r}
library(PKbioanalysis)
```


```{r}
x <- generate_96("Dilution integerity") |> 
  fill_scheme("v", top_bound = "A", bottom_bound = "C") |>
  add_samples(rep("LOQ/4", 3), conc = 0.25, prefix = "S") |>
  fill_scheme("h", left_bound = 2, right_bound = 9) |>
  add_cs_curve(c(1, 3, 5, 10, 20, 50, 100, 200), rep =3) |> # 8 points, 3 replicates
  fill_scheme("h", left_bound = 9, right_bound = 12) |>
  add_DB() |>
  add_blank() |> 
  add_blank() |> 
  add_DQC(conc = 1000, 100, rep = 6) |>
  fill_scheme("h") |>
  add_QC(3, 90, 180, reg = T, n_qc = 6, qc_serial = F) 
```


```{r}
plot(x)
```

```{r}
register_plate(x)
```


```{r}
plate_app()

```