---
title: "Study Design Review"
author: "Omar Elashkar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Study Design Review}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.width = 15,
  fig.height = 10
)
```


```{r}
library(PKbioanalysis)
```


```{r}
study <- generate_96() |> 
    add_samples(1:5, dosage = "A", factor = "M", time = 1:5*30) |>
    add_samples(6:10, dosage = "A", factor = "F", time = 1:5*30) |>
    add_samples(11:15, dosage = "B", factor = "M", time = 1:5*30) |>
    add_samples(16:18, dosage = "B", factor = "F", time = 1:3*30) 

```

```{r}
plot(study)
```

```{r}
plot_design(study)
```


```{r}
data(Indometh)
plate <- generate_96() |> 
  add_samples(
    samples = Indometh$Subject, 
    time = Indometh$time, 
    dosage = "100mg",
    route = "IV",
    cmt = "plasma",
    vtime = TRUE)
```

```{r}
plot(plate, color = "samples")
plot(plate, color = "time")
```

```{r}
plot_design(plate)
```