---
title: "Visualize Chromatograms"
author: "Omar Elashkar"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualize Chromatograms}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.width = 15,
  fig.height = 10
)
```

```{r}
library(PKbioanalysis)
```

We will load Waters `.raw` Chromatograms using `read_chrom()`. We need to have method specified in the `method` argument. This can be done or edited using the interface in `study_app()`.

```{r echo= FALSE}
PKbioanalysis:::.reset_samples_db()
x <- system.file("cmpds.yaml", package = "PKbioanalysis")  |> 
    PKbioanalysis:::.parse_cmpds()  |> suppressWarnings()
PKbioanalysis:::.save_cmpd_db(x)
```

```{r}
chrompath <- system.file("extdata", "waters_raw_ex", package="PKbioanalysis")
chroms <- read_chrom(chrompath, method = 1)
```

```{r}
get_sample_names(chroms)
```

```{r}
plot_chrom(chroms, sample_id = 3, ncol  = 2)
```


More interactive features for integration and visualization are to be added in the future. 